slight restructuring
Put "ok" on the same logical level as the activity statement -  the conditions only check for errors an perform an early bail out.

diff --git a/boinc/files/boinc-client b/boinc/files/boinc-client
--- a/boinc/files/boinc-client
+++ b/boinc/files/boinc-client
@@ -17,31 +17,25 @@ start() {
 
    if ! [ -d "$BOINCDIR" ]; then
       echo -n "Creating $BOINCDIR... "
-      if mkdir -p $BOINCDIR 2>/dev/null ; then
-         echo "[OK]"
-      else
+      if ! mkdir -p $BOINCDIR 2>/dev/null ; then
          echo "[FAILED]"
          return 1
       fi
+      echo "[OK]"
    fi
 
-   echo -n "Checking owner of $BOINCDIR... "
+   echo -n "Checking ownership of $BOINCDIR... "
    BOINCDIR_OWNER="$(ls -ld $BOINCDIR | awk '{print $3}')"
-   if [ "$BOINCUSR" = "$BOINCDIR_OWNER" ] ; then
-      echo "[OK]" 
-   else
-      echo "[FAILED]"
-
-      echo -n "Trying to fix owner... "
+   if [ "$BOINCUSR" != "$BOINCDIR_OWNER" ] ; then
+      echo -n "(fixing)... "
       chown -R $BOINCUSR:$BOINCUSR $BOINCDIR
       BOINCDIR_OWNER="$(ls -ld $BOINCDIR | awk '{print $3}')"
-      if [ "$BOINCUSR" = "$BOINCDIR_OWNER" ] ; then
-         echo "[OK]"
-      else
-         echo "[FAILED]"
+      if [ "$BOINCUSR" != "$BOINCDIR_OWNER" ] ; then
+         echo "[FAILED] ('$BOINCUSR' != '$BOINCDIR_OWNER')"
          return 3
       fi
    fi
+   echo "[OK]"
 
    cd $BOINCDIR
    echo -n "Starting Boinc-client... "
@@ -49,13 +43,11 @@ start() {
                      -x $BOINCEXE_NAME -- $BOINCEXE_OPTS
 
    PID=$( pidof $BOINCEXE_NAME )
-   if ! [ -z "$PID" ]; then
-      echo "[OK]"
-      return 0
-   else
+   if [ -z "$PID" ]; then
       echo "[FAILED]"
       return 4
    fi
+   echo "[OK]"
 }
 
 stop() {
@@ -72,11 +64,10 @@ stop() {
          return 1;
       fi
       echo "[OK]"
-      return 0;
    else
-      echo "I: Boinc was not running."
-      return 0
-   fi
+      echo "[was not running]"
+    fi
+    return 0
 }
 
 restart() {
